### PR TITLE
fix(replies): fix replies from Status and to Status messages

### PR DESCRIPTION
**Pull request by jrainville**
Needed for https://github.com/status-im/status-desktop/issues/16323

There were multiple problems.

1. The ParentID was not set correctly when a message was sent from Status
2. We didn't send back the ID of messages that we sent, so the gateway couldn't associate the new messages to the old ones
3. Missing param in the toml config `PreserveThreading`
4. Discord messages are weirdly formatted when a reply is send. It cannot use webhooks, so we need to pass the username directly in the message (it's ugly, but it works)

Finally, there was an issue on the status-go side. We tried to use the discord message ID to find the replies, but the bridge already converts it to the right ID, so we could just use it directly

How it looks in Status:
image

How it looks in Discord:
image

They all work now. The only sad thing is replies from Status look a bit ugly in Discord, but that's a limitation in the Discord API I think.

### CODE REVIEW

**Comment by jrainville** [comment]
status-go PR https://github.com/status-im/status-go/pull/5830

**Comment by siddarthkay** [comment]
nice @jrainville : once the status-go PR is merged and cherry picked on release 2.30 branch we could use this PR to update the status-go version as well.

**Comment by jrainville** [comment]
> nice @jrainville : once the status-go PR is merged and cherry picked on release 2.30 branch we could use this PR to update the status-go version as well.

Yeah we could. Though as far as I understand, the status-go changes are mostly useful for actual users receiving messages, so we'll need for 2.31 to have the real fix in the hands of users

**Comment by siddarthkay** [comment]
@jrainville : ah thanks for explaining!

**Review by siddarthkay — APPROVED** [review]

**Pull request merged**
