### PR TITLE
fix: Upgrade status-go to the most recent version of release branch w…

### PR DESCRIPTION
**Pull request by endulab**
Upgrade status-go to the most recent version of release branch which contains memory fix.

Fixes:
- https://github.com/status-im/status-go/issues/4990

### CODE REVIEW

**Review by jrainville — APPROVED** [review]

**Review by jakubgs — APPROVED** [review]
I have built this image and deployed it to the host. Lets see if it works the same as the one from `enabling-pprof` branch.

**Comment by jakubgs** [comment]
Question, why is this commit not in `develop`?

- https://github.com/status-im/status-go/commit/d59ff96b54fa

image

It's in [`release/0.177.x`](https://github.com/status-im/status-go/compare/release/0.177.x), but it's not part of `develop` branch.

Is this fix in `develop` at all?

**Comment by endulab** [comment]
> Question, why is this commit not in `develop`?
> 
> * [status-im/status-go@d59ff96b54fa](https://github.com/status-im/status-go/commit/d59ff96b54fa)
> 
> image
> 
> It's in [`release/0.177.x`](https://github.com/status-im/status-go/compare/release/0.177.x), but it's not part of `develop` branch.
> 
> Is this fix in `develop` at all?

The bridge uses status-go release  0.177.x version, not develop.
The memory fix is in both release and develop branches.
There are some discrepancies between release and develop branches now, because some tasks are for RC, some not.
That's probably why Darios commit is in release and not in develop.

**Comment by jakubgs** [comment]
Thanks for the fix.

BTW, this commit title is about twice too long:

image

**Pull request merged**
